inputs:
  image_name:
    description: "Name for the image"
    type: string
  login_url:
    description: "Azure Container Registry login URL"
    type: string
  username:
    description: "Username for the Container repository"
    type: string
  password:
    description: "Password for the Container repository"
    type: string
  version:
    description: "Tag for the image"
    type: string
  GHAS_Enabled:
    description: "True if Github Advance Security Enable for your repo."
    type: bool

runs:
  using: "composite"
  steps:
    - name: Docker login
      shell: bash
      run: |
        docker login ${{ inputs.login_url }} --username ${{ inputs.username }} --password ${{inputs.password}}

    - name: Docker Build Image
      shell: bash
      run: |
        docker build . -t ${{ inputs.login_url }}/${{ inputs.image_name }}:${{ inputs.version }} -t ${{ inputs.login_url }}/${{ inputs.image_name }}:latest

    - name: Docker Publish Image
      shell: bash
      run: |
        docker push ${{ inputs.login_url }}/${{ inputs.image_name }} --all-tags

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.login_url }}/${{ inputs.image_name }}:${{ inputs.version }}
        severity: "CRITICAL,HIGH, MEDIUM"
        format: ${{ inputs.GHAS_Enabled == true && 'sarif' || 'table' }}
        output: "${{ inputs.image_name }}-results.sarif"
        ignore-unfixed: true
        vuln-type: "os,library"

    - name: Upload Trivy scan results to GitHub Security tab
      if: ${{ inputs.GHAS_Enabled == true }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: "${{ inputs.image_name }}-results.sarif"
        category: ${{ inputs.image_name }}

    - name: Uload Trivy scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.image_name }}-results
        path: "${{ inputs.image_name }}-results.sarif"
