name: ci-cd pipeline
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Run Bicep linter
        run: az bicep build --file infra/main.bicep

      # - name: Run PSRule analysis
      #   uses: microsoft/ps-rules@2
      #   with:
      #     modules: PSRule.Rules.Azure

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run preflight validation
        uses: azure/arm-deploy@v1
        with:
          scope: "subscription"
          region: "uksouth"
          template: infra/main.bicep
          deploymentMode: Validate
          parameters: infra/main.parameters.json
        env:
          location: ${{ vars.AZURE_LOCATION }}
          environmentName: ${{ vars.AZURE_ENV_NAME }}
