name: ci-cd pipeline
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  default_region: "uksouth"

jobs:
  build_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # This step is need to downalod module comming from the private tepo
      - name: Run Bicep restore
        run: az bicep restore --file infra/main.bicep

      - name: Run Bicep linter
        run: az bicep build --file infra/main.bicep

      # - name: Run PSRule analysis
      #   uses: microsoft/ps-rules@2
      #   with:
      #     modules: PSRule.Rules.Azure

      - name: Run preflight validation
        uses: azure/arm-deploy@v1
        with:
          scope: "subscription"
          region: ${{ env.default_region }}
          template: infra/main.bicep
          deploymentMode: Validate
          parameters: infra/main.parameters.json location=${{ vars.AZURE_LOCATION }} environmentName=${{ vars.AZURE_ENV_NAME }}

  deploy_infra:
    runs-on: ubuntu-latest
    needs: [build_infra]
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run preflight validation
        uses: azure/arm-deploy@v1
        with:
          scope: "subscription"
          region: ${{ env.default_region }}
          template: infra/main.bicep
          parameters: infra/main.parameters.json location=${{ vars.AZURE_LOCATION }} environmentName=${{ vars.AZURE_ENV_NAME }}
