name: ci-cd pipeline
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  dotnet_version: "8.0"
  GHAS_Enabled: false
  application_image_name: "azure-native-3tier-app"

  CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL }}
  # Set up in github below secrets with credentila for container registry
  # CONTAINER_REGISTRY_USERNAME
  # CONTAINER_REGISTRY_PASSWORD

jobs:
  build_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build bicep
        uses: ./.github/actions/build-bicep
        with:
          Azure_Env_Name: ${{ vars.AZURE_ENV_NAME }}
          Azure_Location: ${{ vars.AZURE_LOCATION }}

  build-app:
    runs-on: ubuntu-latest
    outputs:
      url_provided: ${{ steps.check_url.outputs.url_provided }}
    permissions:
      contents: read # for actions/checkout to fetch code

    steps:
      - name: Check if provide conrainer registry url
        id: check_url
        run: |
          if [[ "$env.CONTAINER_REGISTRY_URL" == "" ]]; then
            echo "url_provided=0" >> "$GITHUB_OUTPUT"
          else
            echo "url_provided=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test dotnet application
        uses: ./.github/actions/build-dotnet-app
        with:
          dotnet_version: ${{ env.dotnet_version }}

  build-image:
    if: ${{ needs.build-app.outputs.url_provided }}
    runs-on: ubuntu-latest
    needs: [build-app, build_infra]
    permissions:
      contents: read # for actions/checkout to fetch code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Publish Docker Image
        uses: ./.github/actions/build-image
        with:
          image_name: ${{ env.application_image_name }}

          login_url: ${{ env.CONTAINER_REGISTRY_URL  }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          version: ${{ github.sha }}
          GHAS_Enabled: ${{ env.GHAS_Enabled }}

  deploy_infra:
    runs-on: ubuntu-latest
    needs: [build_infra, build-image]
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy bicep
        uses: ./.github/actions/deploy-bicep
        with:
          Azure_Env_Name: ${{ vars.AZURE_ENV_NAME }}
          Azure_Location: ${{ vars.AZURE_LOCATION }}
